export const WRITE_USER_NAME = 'WRITE_USER_NAME';
export const START_GAME = 'START_GAME';

export const START_SAVE_SCORE = 'START_SAVE_SCORE';
export const COMPLETE_SAVE_SCORE = 'COMPLETE_SAVE_SCORE';

export const COMPLETE_GAME = 'COMPLETE_GAME';

export const START_FETCH_SCORES = 'START_SAVE_SCORES';
export const FETCH_SCORES = 'SAVE_SCORES';
export const COMPLETE_FETCH_TOP_SCORES = 'COMPLETE_FETCH_TOP_SCORES';
export const COMPLETE_FETCH_SCORES = 'COMPLETE_SAVE_SCORES';
